parameters:
  extension_in: tif 
  #trackpy.batch
  diameter:  9
  minmass:  300
  separation: 12
  #trackpy.link
  search_range: 6
  memory: 5
  adaptive_stop: 5
  adaptive_step: 0.9
  stub_filtering: 3 # Minimum length of trajectories in points
  #trackpy.motion.msd
  msd: 9 # Threshold for MSD filtering
  #SNR estimation
  base_level: 0 #Base level for SNR estimation
  #Rejoining
  threshold_t: 10 # Temporal threshold for trajectory rejoining in frames
  threshold_r: 40 # Spatial threshold for trajectory rejoining in pixels
  #Data Extraction
  r_conf_cut :  0.64 # Confinement ratio cutoff between GO and STOP phases
  px :  0.173 # Pixel size in µm
  dt :  0.05 # Time interaval between frames in s
  min_thr_prec :  50 # Minimum theoretical precision in nm
  sliding_window: 3 # Sliding windows for confinement ratio calculation
  sigma: 129 # Estimated precision of localization
  len_cutoff: 30 # Number of points
  threshold_poly3: 1.4 # Deviation from third-degree polynom
  #Stats
  order: [WT,HET,HOM] # Order of conditions in tables and graph
  extension_out: svg # File extension of saved graphs
  dpi: 300 # DPI of saved graphs if theyre not vectorial


#Optional image and trajectory processing

settings: 
  #Denoising
  tophat: True
  wavelet: False
  #Processing
  stub_filtering: False
  MSD: True
  rejoining: True
  SNR_estimation: True
  #Outputs
  individual_images: False
  individual_txt: False
  group_image: True
  #Data Extraction
  polynomial_fit: True
  minimization: True
  theta: True
  antero_retro: True
  conf_list: True
  #Stats
  ordering: False
  clean_up: False
